volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  app:
    image: docker.io/library/suba:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
